### ISSUE TITLE
After upload file, it say failed but always when I press retry button go OK 

### ISSUE THREAD

**Issue by andresilvagomez** [ahmedkandel/nova-s3-multipart-upload#1]

**Comment by andresilvagomez** [comment]
When I added <ExposeHeader>ETag</ExposeHeader> it works fine !!!

**Comment by ahmedkandel** [comment]
Do you mean ETag in CORS configuration? If so please refer to the documentation https://github.com/ahmedkandel/nova-s3-multipart-upload#%EF%B8%8F-s3-configuration

If not please explain more what do you mean.

**Comment by andresilvagomez** [comment]
@ahmedkandel thats right 👍🏼 good package !!!
