### ISSUE TITLE
Composer: requires laravel/nova ^3.12 -> could not be found in any version

### ISSUE THREAD

**Issue by mulder2222** [ahmedkandel/nova-s3-multipart-upload#11]
When i run `composer require "ahmedkandel/nova-s3-multipart-upload" `I get the following error:

`Problem 1
    - Root composer.json requires ahmedkandel/nova-s3-multipart-upload ^1.2 -> satisfiable by ahmedkandel/nova-s3-multipart-upload[v1.2.0].
    - ahmedkandel/nova-s3-multipart-upload v1.2.0 requires laravel/nova ^3.12 -> could not be found in any version, there may be a typo in the package name.
    - `

We have installed Laravel Nova 3.21.0.
![image](https://user-images.githubusercontent.com/7282422/107539167-fc902800-6bc4-11eb-9386-2f7d45a8614b.png)

Thanks in advance for any help...

**Comment by ahmedkandel** [comment]
Hi @mulder2222, i see you closed the issue, are you still facing this issue?

**Comment by mulder2222** [comment]
@ahmedkandel no.. it turned out i made a mistake. So this was not an issue.
