### ISSUE TITLE
Add a watermark to any video or image uploaded

### ISSUE THREAD

**Issue by SargisBeglaryan** [ahmedkandel/nova-s3-multipart-upload#15]
How can I automatically add watermark  to video or image.

**Comment by ahmedkandel** [comment]
This is out of the package scope, But I may be helpful. The files get uploaded to S3 so the best implementation is to use AWS services for this task. So I think using AWS Elastic Transcoder and a Lambda function will achieve the task, please refer to [this post](https://thecodinginterface.com/blog/aws-transcoding-watermark/). Then you can fire the Lambada function when the model gets updated.

Another suggestion maybe if you need to show the watermark only when displaying you can use front-end javascript libs like [Video.js](https://github.com/videojs/video.js/)
