### ISSUE TITLE
DigitalOcean Spaces or Local Disk Support

### ISSUE THREAD

**Issue by Milkhan** [ahmedkandel/nova-s3-multipart-upload#16]
Thank you for this nice package
Is it possible to make it work with digitalocean or local disk?

**Comment by ahmedkandel** [comment]
I think it should work with DigitalOcean as it has S3 compatible API. While for the local disk it has no sense as the main purpose of this packages is to avoid loading the server as much as it can.

**Comment by ahmedkandel** [comment]
Closed due to inactivity.

**Comment by modernben** [comment]
@ahmedkandel I'm getting an invalid url issue. It looks like there is some rebuilding of URLs going on.


```
"Error executing \"CreateMultipartUpload\" on \"https://dialedhealth.s3.sfo2.amazonaws.com//daily-dialed/2022-07-26/22d877ee-aade-4446-8b89-e721e509eb1b.mp4?uploads\"; AWS HTTP error: cURL error 6: Could not resolve host: dialedhealth.s3.sfo2.amazonaws.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://dialedhealth.s3.sfo2.amazonaws.com//daily-dialed/2022-07-26/22d877ee-aade-4446-8b89-e721e509eb1b.mp4?uploads",
```

Nowhere in my code do I have `s3` or `amazonaws.com`

**Comment by ahmedkandel** [comment]
@modernben it would be better to open a new issue instead of commenting here. Anyway it seems that you have issue in Laravel S3 disk configuration. Can you check?

"Nowhere in my code do I have s3 or amazonaws.com" what do you mean?

**Comment by modernben** [comment]
My disk definition is good to go and working with the rest of the site. In fact, that's what I am using to upload using the File field.
![Screen Shot 2022-07-29 at 9 15 27 AM](https://user-images.githubusercontent.com/67608755/181801410-82788390-e35c-4434-9d65-30431035151e.png)

<img width="467" alt="Screen Shot 2022-07-29 at 9 14 37 AM" src="https://user-images.githubusercontent.com/67608755/181801224-32fe7abb-8efe-4d27-b562-19e9d2ea3eed.png">

The URL in the error (`https://dialedhealth.s3.sfo2.amazonaws.com/`) seems like either this package or the underlying Uppy dependency is rewriting the URL to upload to. It shouldn't be https://dialedhealth.s3.sfo2.amazonaws.com/ it should be https://sfo2.digitaloceanspaces.com/. The same that is in the disk config.
