### ISSUE TITLE
Field is Not Showing

### ISSUE THREAD

**Issue by Milkhan** [ahmedkandel/nova-s3-multipart-upload#17]
Hi, 
I tried to install and use it according to the readme but I couldnt make it work, it's not showing on my resource. No errors, nothing.
PS I have digitalocean as s3 in conf.

BTW Thank you for this nice package

**Comment by ahmedkandel** [comment]
Can you share some more information like the source code of your Nova Resource and access to an online instance of the project or some debug information?

**Comment by ahmedkandel** [comment]
Closed due to inactivity.
