### ISSUE TITLE
New function: View file in browser or download it

### ISSUE THREAD

**Issue by andresilvagomez** [ahmedkandel/nova-s3-multipart-upload#2]
I wana to create a funtion like to this capture

<img width="1783" alt="Captura de Pantalla 2020-12-03 a la(s) 11 06 26 p  m" src="https://user-images.githubusercontent.com/2415015/101120726-5cae9080-35bc-11eb-9bce-ab3816052f0b.png">

what do you think is the best way to implement it?

maybe something like 

`->onlyView()`
`->onlyDownload()` <- this is the default maybe don't be appear 
`->viewAndDownload()`

**Comment by ahmedkandel** [comment]
I think it is better to name it `->contentDisposition()` which will accept `$type` as a parameter with values either `inline` for view in browser or `attachment` for download.

I don't think having both view and download actions have sense but you can achieve this by passing the `$type` value as `both`.

For sure this function needs implementation so PRs are welcome.

**Comment by andresilvagomez** [comment]
Here the PR => https://github.com/ahmedkandel/nova-s3-multipart-upload/pull/3

**Comment by ahmedkandel** [comment]
Thanks to @andresilvagomez Closed by #3
