### ISSUE TITLE
Field doesn't show?

### ISSUE THREAD

**Issue by hassan-knopsmedia** [ahmedkandel/nova-s3-multipart-upload#20]
I am trying to upload multiple files locally but the field doesn't show or S3 is a must for this field to be able to show?

Nova field:
`NovaS3MultipartUpload::make(__('Upload Files'), 'files')
				->storeAsMultipleArray('file_path')
				->disk('public')
				->path('public/Orders')
				->storeName('file_name')
				->storeSize('file_size')
				->keepOriginalName()
				->allowMultipleUploads()
				->displayPoweredByUppy(),`

Model:
`protected $fillable = ['files'];
	/**
	 * The attributes that should be cast to native types.
	 *
	 * @var array
	 */
	protected $casts = [
		'files' => 'array',
	];`

**Comment by ahmedkandel** [comment]
this package works only with S3 disks.
