### ISSUE TITLE
Question: Support for nova 4?

### ISSUE THREAD

**Issue by tractorcow** [ahmedkandel/nova-s3-multipart-upload#27]
Thank you for this module. Will there be any chance of this module being updated for nova 4? We recently updated and are looking at the upgrade path required.

**Comment by ahmedkandel** [comment]
Hi @tractorcow ,

I have this upgrade in mind and already got a PR #26 from @ngunyimacharia but it needs some review before merging and we are currently very very busy at the work. I hope we got this chance very soon.

**Comment by tractorcow** [comment]
Hi @ahmedkandel , thanks for the update. I'm happy to check out that PR and assist with testing and help getting it over the line. Fortunately I am busy with work, but upgrading nova 4 is my work too. :)

**Comment by chrillep** [comment]
@ahmedkandel same :)

**Comment by Israr22** [comment]
Hi @ahmedkandel, I am still waiting for this update. kindly done ASAP.
Thank You

**Comment by sietse85** [comment]
have a feeling this update won't come. i'm running into file upload issues with laravel nova 4 as well. perhaps its best to just fork and make the changes yourself.

**Comment by tractorcow** [comment]
@sietse85 test the PR at https://github.com/ahmedkandel/nova-s3-multipart-upload/pull/26; We had some success with that

**Comment by SatishNidhi** [comment]
Hi @ahmedkandel, Is this package is not available for nova 4 ?

**Comment by ahmedkandel** [comment]
Hi,

I'm really sorry for not having time to upgrade the plugin to Nova 4 or review the PR #26 .
@tractorcow @mykkode @chrillep @sietse85 can you please test and review with feedback the PR by @ngunyimacharia ?
If you could give me your feedback i will merge it immediately.

**Comment by ahmedkandel** [comment]
Hey,
 the support for Nova v4 has been added thanks to PR #26 from @ngunyimacharia , can anyone how is interested install the package  for test and let me know if all is ok?
